### PR TITLE
fix: properly print key class

### PR DESCRIPTION
**Pull request by TimoGlastra**
This makes sure that at least in the ConsoleLogger the `Key` class is printend as the `fingerprint` property, so we avoid this:

```
{
    "publicKey": {
      "type": "Buffer",
      "data": [
        67,
        227,
        94,
        17,
        202,
        44,
        168,
        217,
        210,
        62,
        120,
        65,
        119,
        12,
        186,
        150,
        210,
        1,
        153,
        142,
        54,
        158,
        119,
        223,
        138,
        189,
        1,
        4,
        72,
        145,
        192,
        23
      ]
    },
    "keyType": "ed25519"
  }
```

### CODE REVIEW

**Comment by berendsliedrecht** [comment]
Won't this cause any issues with the `JsonEncoder` or any `JSON.stringify` function?

**Comment by TimoGlastra** [comment]
Yes it will, and I've been thinking about that as well, but you shouldn't really put a `Key` class into a `JsonEncoder` or `JSON.stringify`, so I thought how bad is it in that case if it encodes it to a multibase string (contains both the key type + encoding scheme)? But maybe the toJSON should rather be an object with keytype + publicKeyBase58?

**Comment by genaris** [comment]
> But maybe the toJSON should rather be an object with keytype + publicKeyBase58?

I would say this might be more appropriate, as it would return a JSON object as it does today but in a more meaningful way than serializing a buffer instance.

**Comment by TimoGlastra** [comment]
> I would say this might be more appropriate, as it would return a JSON object as it does today but in a more meaningful way than serializing a buffer instance.

Done ✅

**Review by genaris — APPROVED** [review]

**Pull request merged**
